### ISSUE TITLE
Add repo topics

### ISSUE THREAD

**Issue by jameslamb** [UptakeOpenSource/fRanz#21]
@mjermann @Paxanator this one has to be done by maintainers...add some topic tags on this repo so we could be discovered in places like https://github.com/topics/kafka!

My best guess is `r`, `kafka`, `c++`, `streaming`

**Comment by Paxanator** [comment]
> @mjermann @Paxanator this one has to be done by maintainers...add some topic tags on this repo so we could be discovered in places like https://github.com/topics/kafka!
> 
> My best guess is `r`, `kafka`, `c++`, `streaming`

Thanks!
