### ISSUE TITLE
Rcpp-generated functions should be internal

### ISSUE THREAD

**Issue by jameslamb** [UptakeOpenSource/fRanz#31]
While looking at this project today, I noticed that these functions are all currently exported in the package namespace:

```
export(GetRdConsumer)
export(GetRdProducer)
export(KafkaConsume)
export(KafkaProduce)
export(RdSubscribe)
```

From the example in the README, it seems to me that you want the main interface people use to be the R6 classes `KafkaBroker`, `KafkaConsumer`, and `KafkaProducer`. Given that, I think you should bring all of these functions inside the package namespace to reduce your possible maintenance burden and to be sure people use the main pattern you're encouraging.

**Comment by mjermann** [comment]
great catch! I'm all for consolidating our interface.
